### ISSUE TITLE
Проблема!

### ISSUE THREAD

**Issue by TofaDev** [U61vashka/PlasmoVoiceAddon#1]
Здравствуйте, столкнулся с такой проблемой: Плагин слишком крутой.. Подскажите пожалуйста, что делать?

**Comment by bivashy** [comment]
Нам известно об этой проблеме. Надеемся что она будет решена в ближайшее время. Простите за доставленные неудобства

**Comment by bivashy** [comment]
Данная серьезная недоработка была исправлена! Поздравляю!

This serious issue was resolver! Congratulations!
