### ISSUE TITLE
Добавление в PlasmoVoice

### ISSUE THREAD

**Issue by bottleofench** [U61vashka/PlasmoVoiceAddon#3]
**Привет!** Твой плагин очень неплохой, и мне кажется, что было бы неплохо сделать так, чтобы больше людей его использовали, хоть и в облегченном формате.

Поэтому, я планирую встроить код из твоего плагина в сам PlasmoVoice для создания дополнительного API, само собой с указанием твоего авторства.
Планирую добавить два метода `playMusicToPlayerFromFile()` и `playMusicToPlayerFromUrl()` в API.  
Не будешь ли ты против этого? Потому что такое добавление улушчит плагин и увеличит простор для фантазий сторонних разработчиков!

Ну и понятное дело, что если ты не захочешь этого, то и добавлять я это не буду.

**Comment by bivashy** [comment]
Не против, удачи с этим! 
Извиняюсь за долгий ответ, по какой то причине у меня не приходили уведомления связанные с этим репозиторием.

**Comment by bivashy** [comment]
Мой ответ да, так что я думаю могу закрыть это.

My answer is yes, so probably i can close this.
